import Link from "next/link";
import { Icon, SiteShell } from "./components";
import { portfolioItems, services } from "./data";

const reasons = ["Creative and modern design approach", "Professional quality work", "Fast delivery and clear communication", "SEO-friendly website structure", "Mobile responsive designs", "Brand-focused digital solutions", "Affordable and result-driven services", "Complete creative support in one place"];
const testimonials = [["S", "Sarah Khan", "Business Owner", "Zephtrix Studio delivered high-quality designs that improved our brand image. Professional, fast, and creative."], ["A", "Ahmed R.", "Content Creator", "The video editing and motion graphics work was amazing. Highly recommended for digital creators and businesses."], ["M", "Maria Ali", "Startup Founder", "Our website looks modern, fast, and professional. The team understood our vision perfectly."]];

export default function Home() {
  return <SiteShell active="Home">
    <section className="campaign-hero"><div className="container"><div className="section-eyebrow">Premium Creative Studio</div><h1 className="campaign-headline">Zephtrix Studio -<br />Creative Design, Motion &amp;<br />Digital Growth Solutions</h1><p className="campaign-sub">We help brands grow with powerful visuals, stunning videos, modern websites, UI/UX designs, motion graphics, and result-driven social media marketing.</p><div className="campaign-actions"><Link href="/portfolio" className="pill pill-primary"><Icon name="fa-eye" /> View Our Work</Link><Link href="/contact" className="pill pill-outline"><Icon name="fa-arrow-right" /> Start Your Project</Link></div></div></section>
    <section><div className="container text-center"><div className="section-eyebrow">About</div><h2 className="section-title">Turning Ideas Into <strong>Digital Experiences</strong></h2><p className="section-subtitle">At Zephtrix Studio, we turn ideas into powerful digital experiences. From eye-catching graphic design to high-converting WordPress websites and professional video editing, we create digital content that makes brands stand out.</p></div></section>
    <section><div className="container"><div className="color-block coral"><div className="text-center"><div className="section-eyebrow">What We Do</div><h2 className="section-title">Our <strong>Services</strong></h2><p className="section-subtitle">Complete creative solutions to grow your brand with design, video, web, and marketing.</p></div><div className="grid-3 service-block-grid">{services.map((service) => <div className="service-card" key={service.title}><div className="icon"><Icon name={service.icon} /></div><h3>{service.title}</h3><p>{service.description}</p></div>)}</div><div className="text-center section-link"><Link href="/services" className="pill pill-primary">Explore All Services <Icon name="fa-arrow-right" /></Link></div></div></div></section>
    <section><div className="container"><div className="text-center"><div className="section-eyebrow">Why Us</div><h2 className="section-title">Why Choose <strong>Zephtrix Studio?</strong></h2></div><div className="why-grid">{reasons.map((reason) => <div className="why-item" key={reason}><Icon name="fa-check" /><span>{reason}</span></div>)}</div></div></section>
    <section><div className="container"><div className="color-block navy"><div className="grid-4 stats">{[["100+", "Projects Completed"], ["50+", "Happy Clients"], ["12", "Creative Services"], ["24/7", "Client Support"]].map(([number, label]) => <div key={label}><div className="stat-number">{number}</div><div className="stat-label">{label}</div></div>)}</div></div></div></section>
    <section><div className="container"><div className="text-center"><div className="section-eyebrow">Portfolio</div><h2 className="section-title">Featured <strong>Work</strong></h2></div><div className="grid-3">{portfolioItems.slice(0, 6).map(([title, category, , icon]) => <div className="portfolio-card" key={title}><div className="thumb"><Icon name={icon} /></div><div className="info"><h4>{title}</h4><span>{category}</span></div></div>)}</div></div></section>
    <section className="section-soft"><div className="container"><div className="text-center"><div className="section-eyebrow">Testimonials</div><h2 className="section-title">What <strong>Clients Say</strong></h2></div><div className="grid-3">{testimonials.map(([initial, name, role, quote]) => <div className="testimonial-card" key={name}><div className="quote"><Icon name="fa-quote-left" /></div><p>&quot;{quote}&quot;</p><div className="author"><div className="avatar">{initial}</div><div><div className="name">{name}</div><div className="role">{role}</div></div></div></div>)}</div></div></section>
    <section><div className="container"><div className="color-block text-center"><div className="section-eyebrow">Let&apos;s Create</div><h2 className="display-title">Ready to Build Something <strong>Creative?</strong></h2><p className="section-subtitle">Let Zephtrix Studio help you create powerful visuals, videos, websites, and marketing content that make your brand stand out.</p><Link href="/contact" className="pill pill-primary">Contact Us Today <Icon name="fa-arrow-right" /></Link></div></div></section>
  </SiteShell>;
}
