export const services = [
  { slug: "app-development", title: "App Development", icon: "fa-mobile-alt", description: "Native and cross-platform mobile apps for Android, iOS, and beyond, built for performance and scale." },
  { slug: "saas-website", title: "SaaS Website", icon: "fa-cloud", description: "Conversion-focused SaaS marketing sites and landing pages built to turn visitors into subscribers." },
  { slug: "paas-website", title: "PaaS Website", icon: "fa-cubes", description: "Platform-as-a-service websites and portals designed for onboarding, integrations, and scale." },
  { slug: "web-development", title: "Web Development", icon: "fa-code", description: "Custom high-performance websites and web applications tailored to your business goals." },
  { slug: "wordpress-development", title: "WordPress Development", icon: "fa-wordpress", description: "Fast, responsive, SEO-friendly WordPress websites for businesses and online brands." },
  { slug: "custom-software", title: "Custom Software", icon: "fa-laptop-code", description: "Bespoke software built end-to-end around your exact business processes and requirements." },
  { slug: "custom-web-software", title: "Custom Web Software", icon: "fa-globe", description: "Custom web-based applications and internal tools, built and hosted entirely in the browser." },
  { slug: "custom-dashboard", title: "Custom Dashboard", icon: "fa-tachometer-alt", description: "Data-rich admin dashboards and analytics interfaces built for clarity and fast decision-making." },
  { slug: "ai-automation", title: "AI Automation", icon: "fa-brain", description: "AI-powered workflows, chatbots, and process automation that cut manual work and scale with your business." },
];

export const portfolioItems = [
  {
    slug: "enterprise-task-management-app", title: "Enterprise Task Management App", category: "App Development", filterKey: "app", icon: "fa-mobile-alt",
    description: "A cross-platform mobile app for assigning, tracking, and reporting on team tasks in real time across large organizations.",
    image: "/portfolio-task-management.png", client: "Horizon Logistics",
    overview: "Horizon Logistics needed a single app to replace a patchwork of spreadsheets and chat threads for coordinating work across dozens of teams. We built a cross-platform task management app with real-time updates, team collaboration, and reporting built in from day one.",
    features: ["Real-time task assignment and tracking", "Team collaboration with comments and mentions", "Automated progress reports and analytics", "Push notifications for deadlines", "Cross-platform: iOS, Android, Web, Windows", "Role-based team permissions"],
    technologies: ["React Native", "Node.js", "PostgreSQL", "WebSockets"],
    result: "Cut average task turnaround time by 32% within the first quarter of rollout.",
  },
  {
    slug: "fitness-tracking-mobile-app", title: "Fitness Tracking Mobile App", category: "App Development", filterKey: "app", icon: "fa-mobile-alt",
    description: "A native fitness app with workout logging, progress charts, and personalized plans built for daily engagement.",
    image: "/portfolio-fitness-app.png", client: "PulseFit Studios",
    overview: "PulseFit Studios wanted a companion app that would keep members engaged between gym visits. We designed a fitness app centered on daily habits — workout logging, progress visualization, and personalized plans that adapt to each user's goals.",
    features: ["Workout logging with sets, reps, and weights", "Personalized workout and nutrition plans", "Real-time progress charts and body stats", "Daily activity and step tracking", "Achievement badges and streak tracking", "Health insights dashboard"],
    technologies: ["Flutter", "Firebase", "HealthKit", "Google Fit API"],
    result: "Grew daily active users by 45% in the first 90 days post-launch.",
  },
  {
    slug: "saas-analytics-platform-website", title: "SaaS Analytics Platform Website", category: "SaaS Website", filterKey: "saas", icon: "fa-cloud",
    description: "A conversion-focused marketing site and product tour for a data analytics SaaS, built to turn trial signups into subscribers.",
    image: "/portfolio-saas-analytics.png", client: "InsightPro",
    overview: "InsightPro's old site undersold their product. We rebuilt it around a clear product story — a live dashboard preview, feature breakdowns, and social proof — engineered to move visitors from curious to signed up with as little friction as possible.",
    features: ["Interactive product tour and demo", "Pricing and plan comparison pages", "Customer testimonials and social proof", "Funnel-optimized signup flow", "Live analytics dashboard preview", "SEO-optimized content pages"],
    technologies: ["Next.js", "Tailwind CSS", "Vercel", "PostHog"],
    result: "Increased trial-to-paid conversion rate by 27%.",
  },
  {
    slug: "subscription-billing-saas-site", title: "Subscription Billing SaaS Site", category: "SaaS Website", filterKey: "saas", icon: "fa-cloud",
    description: "A pricing-led SaaS website with plan comparison, billing FAQs, and a streamlined signup flow to reduce checkout drop-off.",
    image: "/portfolio-billing-saas.png", client: "Billdo",
    overview: "Billdo helps businesses manage subscription billing, so their own site needed to make pricing and trust immediately obvious. We led with a transparent pricing page and stripped the signup flow down to the essentials.",
    features: ["Transparent pricing page with monthly/annual toggle", "Billing FAQ and documentation hub", "Streamlined signup and checkout flow", "Customer dashboard preview", "Integration marketplace showcase", "Trust badges and security messaging"],
    technologies: ["Next.js", "Stripe", "Tailwind CSS", "Vercel"],
    result: "Reduced checkout drop-off by 21% after the redesign.",
  },
  {
    slug: "developer-platform-portal", title: "Developer Platform Portal", category: "PaaS Website", filterKey: "paas", icon: "fa-cubes",
    description: "A developer-facing PaaS portal with API docs, onboarding guides, and an integration marketplace to speed up adoption.",
    image: "/portfolio-dev-platform.png", client: "Nexora",
    overview: "Nexora's developer portal is the first thing new integrators see. We built it around fast onboarding — live API references, copy-paste code samples in six languages, and a quickstart guide that gets a working request out the door in minutes.",
    features: ["Interactive API reference with live code samples", "Multi-language SDK documentation", "Developer onboarding quickstart guides", "Integration marketplace", "Usage and rate-limit dashboard", "Community support center"],
    technologies: ["Next.js", "GraphQL", "Docker", "Redis"],
    result: "Cut average developer time-to-first-API-call from 40 minutes to under 10.",
  },
  {
    slug: "corporate-business-website", title: "Corporate Business Website", category: "Web Development", filterKey: "web", icon: "fa-code",
    description: "A fast, SEO-optimized corporate website with a custom CMS, built to represent the brand and generate qualified leads.",
    image: "/portfolio-corporate-website.png", client: "Nexora Solutions",
    overview: "Nexora Solutions needed a corporate site that could keep up with a growing case-study library and services list without waiting on developers for every update. We paired a custom CMS with a fast, SEO-first build.",
    features: ["Custom CMS for non-technical content updates", "Service and industry landing pages", "Case studies and success stories", "Blog and insights hub", "Lead-capture contact forms", "Multi-office location pages"],
    technologies: ["Next.js", "Sanity CMS", "Tailwind CSS"],
    result: "Generated a 38% increase in qualified inbound leads within 6 months.",
  },
  {
    slug: "ecommerce-web-application", title: "E-commerce Web Application", category: "Web Development", filterKey: "web", icon: "fa-code",
    description: "A custom e-commerce platform with product catalog, cart, and checkout, built for performance at scale.",
    image: "/portfolio-ecommerce.png", client: "ShopVista",
    overview: "ShopVista outgrew their off-the-shelf storefront. We built a custom e-commerce platform tuned for their catalog size and traffic, with the checkout flow treated as the most important page on the site.",
    features: ["Full product catalog with filtering and search", "Cart, checkout, and secure payments", "Order tracking and customer accounts", "Inventory and discount management", "Wishlist and product reviews", "Mobile-optimized shopping experience"],
    technologies: ["Next.js", "Stripe", "PostgreSQL", "Redis"],
    result: "Delivered a 99.9%-uptime storefront processing thousands of orders per month.",
  },
  {
    slug: "real-estate-wordpress-website", title: "Real Estate WordPress Website", category: "WordPress Development", filterKey: "wordpress", icon: "fa-wordpress",
    description: "A responsive WordPress site with property listings, search filters, and lead-capture forms for a real estate brand.",
    image: "/portfolio-real-estate.png", client: "Urbanest Real Estate",
    overview: "Urbanest needed a listings site their agents could update themselves. We built it on WordPress with a searchable, filterable property grid and inquiry forms wired straight to their sales team.",
    features: ["Property listing search with map and filters", "For-sale and for-rent property galleries", "Agent profile pages", "Mortgage and price calculator", "Lead-capture inquiry forms", "Fully responsive, SEO-optimized pages"],
    technologies: ["WordPress", "Elementor", "ACF", "WP Rocket"],
    result: "Property inquiries increased 3x within the first two months live.",
  },
  {
    slug: "restaurant-wordpress-website", title: "Restaurant WordPress Website", category: "WordPress Development", filterKey: "wordpress", icon: "fa-home",
    description: "A WordPress website with online menu, reservation booking, and location pages for a multi-branch restaurant.",
    image: "/portfolio-restaurant.png", client: "Flavoria",
    overview: "Flavoria runs three branches and was taking reservations by phone only. We built a WordPress site with a shared menu system, online table booking, and dedicated pages for each location.",
    features: ["Online menu with categories and pricing", "Table reservation booking system", "Multi-branch location pages", "Event and catering inquiry forms", "Photo gallery and social integration", "Fast, mobile-first design"],
    technologies: ["WordPress", "Elementor", "WP Rocket"],
    result: "Online reservations grew to over 60% of total bookings within 3 months.",
  },
  {
    slug: "custom-inventory-management-system", title: "Custom Inventory Management System", category: "Custom Software", filterKey: "software", icon: "fa-laptop-code",
    description: "A bespoke inventory system with stock tracking, supplier management, and automated low-stock alerts.",
    image: "/portfolio-inventory-system.png", client: "StockMaster Supply Co.",
    overview: "StockMaster was tracking inventory across multiple warehouses in spreadsheets, which meant stockouts were routine. We built a custom system that tracks stock in real time and automates the reordering workflow.",
    features: ["Real-time stock level tracking", "Automated low-stock alerts", "Supplier and purchase order management", "Warehouse and location transfers", "Sales and stock movement reporting", "Role-based staff access"],
    technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
    result: "Reduced stockout incidents by 40% in the first quarter.",
  },
  {
    slug: "client-portal-web-application", title: "Client Portal Web Application", category: "Custom Web Software", filterKey: "websoftware", icon: "fa-globe",
    description: "A browser-based client portal for project updates, file sharing, and invoicing, replacing scattered email threads.",
    image: "/portfolio-client-portal.png", client: "Nexora",
    overview: "Nexora's clients were chasing project updates over email. We built a client portal that centralizes progress, files, invoices, and messaging in one place, so status updates happen automatically instead of on request.",
    features: ["Project progress dashboards", "Secure file sharing and document storage", "Invoicing and online payments", "In-app messaging with the team", "Milestone and deadline tracking", "Real-time notifications"],
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Stripe"],
    result: "Cut client status-update emails by over 70% after launch.",
  },
  {
    slug: "business-analytics-dashboard", title: "Business Analytics Dashboard", category: "Custom Dashboard", filterKey: "dashboard", icon: "fa-tachometer-alt",
    description: "A real-time analytics dashboard turning raw business data into clear charts and exportable reports for decision-makers.",
    image: "/portfolio-business-dashboard.png", client: "BizInsights",
    overview: "BizInsights' leadership team was compiling weekly performance reports by hand. We built a live dashboard that pulls their data automatically and turns it into the charts and reports they were building manually before.",
    features: ["Real-time revenue and customer metrics", "Custom, exportable reports", "Multi-channel revenue breakdown", "Regional sales performance views", "Automated alerts on key metric changes", "Role-based dashboard access"],
    technologies: ["React", "D3.js", "Node.js", "PostgreSQL"],
    result: "Cut time spent compiling weekly reports from hours to minutes.",
  },
] as const;

export const serviceDetails = [
  { slug: "app-development", title: "App Development - Android, iOS and Cross-Platform", description: "We build powerful, user-friendly mobile applications for Android, iOS, and cross-platform environments, engineered for performance from the first line of code.", items: ["Native Android app development", "iOS app development", "Cross-platform apps", "UI/UX for mobile apps", "App testing and deployment", "API integration", "App store optimization", "Maintenance and updates", "Push notification integration"], technologies: ["React", "TypeScript", "Node.js", "GitHub"], tone: "service-light" },
  { slug: "saas-website", title: "SaaS Website and Product Design", description: "We design and build SaaS websites, landing pages, and product interfaces engineered to turn visitors into subscribers and subscribers into long-term customers.", items: ["SaaS landing page design", "SaaS dashboard UI/UX", "Pricing page design", "Feature page design", "SaaS website development", "User onboarding design", "Subscription management", "Conversion optimization", "Analytics and tracking integration"], technologies: ["Next.js", "React", "Tailwind CSS", "Vercel", "Stripe"], tone: "service-dark" },
  { slug: "paas-website", title: "PaaS Website and Platform Design", description: "We design and build platform-as-a-service websites and portals — the front door to your platform, built for developer onboarding, integrations, and scale.", items: ["Platform landing page design", "Developer portal design", "API documentation pages", "Integration marketplace pages", "Onboarding flow design", "Usage dashboard design", "Multi-tenant architecture support", "Conversion optimization", "Developer SDK documentation"], technologies: ["Next.js", "Node.js", "Docker", "AWS", "GitHub"], tone: "service-light" },
  { slug: "web-development", title: "Professional Web Development", description: "We develop custom, high-performance websites and web applications tailored to your brand and business goals, optimized for speed, SEO, and user experience.", items: ["Custom website development", "E-commerce websites", "Business websites", "Portfolio websites", "Landing pages", "Web application development", "CMS integration", "Performance optimization", "Security implementation"], technologies: ["Next.js", "React", "Tailwind CSS", "Node.js", "Vercel"], tone: "service-dark" },
  { slug: "wordpress-development", title: "Responsive WordPress Website Development", description: "We build fast, responsive, SEO-friendly, and professional WordPress websites for businesses, agencies, portfolios, and online brands.", items: ["Business websites", "Portfolio websites", "Agency websites", "Landing pages", "Blog websites", "Elementor websites", "Contact forms", "Speed optimization", "Mobile responsive design"], technologies: ["AWS", "GitHub", "Docker"], tone: "service-light" },
  { slug: "custom-software", title: "Custom Software Development", description: "We build bespoke software end-to-end, engineered around your exact business processes rather than forcing your workflow to fit an off-the-shelf product.", items: ["Requirements and process mapping", "Custom backend systems", "Database design and architecture", "Third-party API integration", "Legacy system modernization", "Automated testing", "Deployment and DevOps setup", "Ongoing support and maintenance", "Scalable cloud architecture"], technologies: ["Node.js", "PostgreSQL", "Docker", "AWS", "TypeScript"], tone: "service-dark" },
  { slug: "custom-web-software", title: "Custom Web Software Development", description: "We build custom web-based applications and internal tools that run entirely in the browser — no installs, accessible from anywhere, built around your team's exact workflow.", items: ["Internal tools and admin panels", "Workflow and process automation", "Multi-user web applications", "Role-based access control", "Real-time data features", "Cloud deployment and hosting", "API and integration development", "Ongoing support and maintenance", "Custom reporting tools"], technologies: ["React", "Node.js", "PostgreSQL", "TypeScript", "Docker"], tone: "service-light" },
  { slug: "custom-dashboard", title: "Custom Dashboard Development", description: "We design and build data-rich admin dashboards and analytics interfaces that turn raw data into clear, fast decisions for you and your team.", items: ["Admin dashboard design", "Analytics and reporting UI", "Role-based access views", "Real-time data visualization", "Custom widget development", "Dashboard performance optimization", "Integration with existing APIs", "Ongoing support and maintenance", "Data export and scheduled reports"], technologies: ["React", "PostgreSQL", "Node.js", "TypeScript"], tone: "service-dark" },
  { slug: "ai-automation", title: "AI Automation", description: "We design and build AI-powered automation that removes manual work from your business — from customer-facing chatbots to internal workflows that run themselves.", items: ["AI chatbots and virtual assistants", "Workflow and task automation", "Custom AI integrations (LLM/API)", "Document and data processing automation", "AI-powered internal tools", "Third-party automation platform setup", "Automated reporting and alerts", "Ongoing support and maintenance", "Natural language processing pipelines"], technologies: ["OpenAI", "Node.js", "Docker", "AWS"], tone: "service-light" },
] as const;
