export const services = [
  { title: "App Development", icon: "fa-mobile-alt", description: "Native and cross-platform mobile apps for Android, iOS, and beyond, built for performance and scale." },
  { title: "SaaS Website", icon: "fa-cloud", description: "Conversion-focused SaaS marketing sites and landing pages built to turn visitors into subscribers." },
  { title: "PaaS Website", icon: "fa-cubes", description: "Platform-as-a-service websites and portals designed for onboarding, integrations, and scale." },
  { title: "Web Development", icon: "fa-code", description: "Custom high-performance websites and web applications tailored to your business goals." },
  { title: "WordPress Development", icon: "fa-wordpress", description: "Fast, responsive, SEO-friendly WordPress websites for businesses and online brands." },
  { title: "Custom Software", icon: "fa-laptop-code", description: "Bespoke software built end-to-end around your exact business processes and requirements." },
  { title: "Custom Web Software", icon: "fa-globe", description: "Custom web-based applications and internal tools, built and hosted entirely in the browser." },
  { title: "Custom Dashboard", icon: "fa-tachometer-alt", description: "Data-rich admin dashboards and analytics interfaces built for clarity and fast decision-making." },
  { title: "AI Automation", icon: "fa-brain", description: "AI-powered workflows, chatbots, and process automation that cut manual work and scale with your business." },
];

export const portfolioItems = [
  ["Enterprise Task Management App", "App Development", "app", "fa-mobile-alt", "A cross-platform mobile app for assigning, tracking, and reporting on team tasks in real time across large organizations.", "/portfolio-task-management.png"],
  ["Fitness Tracking Mobile App", "App Development", "app", "fa-mobile-alt", "A native fitness app with workout logging, progress charts, and personalized plans built for daily engagement.", "/portfolio-fitness-app.png"],
  ["SaaS Analytics Platform Website", "SaaS Website", "saas", "fa-cloud", "A conversion-focused marketing site and product tour for a data analytics SaaS, built to turn trial signups into subscribers.", "/portfolio-saas-analytics.png"],
  ["Subscription Billing SaaS Site", "SaaS Website", "saas", "fa-cloud", "A pricing-led SaaS website with plan comparison, billing FAQs, and a streamlined signup flow to reduce checkout drop-off.", "/portfolio-billing-saas.png"],
  ["Developer Platform Portal", "PaaS Website", "paas", "fa-cubes", "A developer-facing PaaS portal with API docs, onboarding guides, and an integration marketplace to speed up adoption.", "/portfolio-dev-platform.png"],
  ["Corporate Business Website", "Web Development", "web", "fa-code", "A fast, SEO-optimized corporate website with a custom CMS, built to represent the brand and generate qualified leads.", "/portfolio-corporate-website.png"],
  ["E-commerce Web Application", "Web Development", "web", "fa-code", "A custom e-commerce platform with product catalog, cart, and checkout, built for performance at scale.", "/portfolio-ecommerce.png"],
  ["Real Estate WordPress Website", "WordPress Development", "wordpress", "fa-wordpress", "A responsive WordPress site with property listings, search filters, and lead-capture forms for a real estate brand.", "/portfolio-real-estate.png"],
  ["Restaurant WordPress Website", "WordPress Development", "wordpress", "fa-home", "A WordPress website with online menu, reservation booking, and location pages for a multi-branch restaurant.", "/portfolio-restaurant.png"],
  ["Custom Inventory Management System", "Custom Software", "software", "fa-laptop-code", "A bespoke inventory system with stock tracking, supplier management, and automated low-stock alerts.", "/portfolio-inventory-system.png"],
  ["Client Portal Web Application", "Custom Web Software", "websoftware", "fa-globe", "A browser-based client portal for project updates, file sharing, and invoicing, replacing scattered email threads.", "/portfolio-client-portal.png"],
  ["Business Analytics Dashboard", "Custom Dashboard", "dashboard", "fa-tachometer-alt", "A real-time analytics dashboard turning raw business data into clear charts and exportable reports for decision-makers.", "/portfolio-business-dashboard.png"],
] as const;

export const serviceDetails = [
  ["App Development - Android, iOS and Cross-Platform", "We build powerful, user-friendly mobile applications for Android, iOS, and cross-platform environments, engineered for performance from the first line of code.", ["Native Android app development", "iOS app development", "Cross-platform apps", "UI/UX for mobile apps", "App testing and deployment", "API integration", "App store optimization", "Maintenance and updates"], "service-light"],
  ["SaaS Website and Product Design", "We design and build SaaS websites, landing pages, and product interfaces engineered to turn visitors into subscribers and subscribers into long-term customers.", ["SaaS landing page design", "SaaS dashboard UI/UX", "Pricing page design", "Feature page design", "SaaS website development", "User onboarding design", "Subscription management", "Conversion optimization"], "service-dark"],
  ["PaaS Website and Platform Design", "We design and build platform-as-a-service websites and portals — the front door to your platform, built for developer onboarding, integrations, and scale.", ["Platform landing page design", "Developer portal design", "API documentation pages", "Integration marketplace pages", "Onboarding flow design", "Usage dashboard design", "Multi-tenant architecture support", "Conversion optimization"], "service-light"],
  ["Professional Web Development", "We develop custom, high-performance websites and web applications tailored to your brand and business goals, optimized for speed, SEO, and user experience.", ["Custom website development", "E-commerce websites", "Business websites", "Portfolio websites", "Landing pages", "Web application development", "CMS integration", "Performance optimization", "Security implementation"], "service-dark"],
  ["Responsive WordPress Website Development", "We build fast, responsive, SEO-friendly, and professional WordPress websites for businesses, agencies, portfolios, and online brands.", ["Business websites", "Portfolio websites", "Agency websites", "Landing pages", "Blog websites", "Elementor websites", "Contact forms", "Speed optimization", "Mobile responsive design"], "service-light"],
  ["Custom Software Development", "We build bespoke software end-to-end, engineered around your exact business processes rather than forcing your workflow to fit an off-the-shelf product.", ["Requirements and process mapping", "Custom backend systems", "Database design and architecture", "Third-party API integration", "Legacy system modernization", "Automated testing", "Deployment and DevOps setup", "Ongoing support and maintenance"], "service-dark"],
  ["Custom Web Software Development", "We build custom web-based applications and internal tools that run entirely in the browser — no installs, accessible from anywhere, built around your team's exact workflow.", ["Internal tools and admin panels", "Workflow and process automation", "Multi-user web applications", "Role-based access control", "Real-time data features", "Cloud deployment and hosting", "API and integration development", "Ongoing support and maintenance"], "service-light"],
  ["Custom Dashboard Development", "We design and build data-rich admin dashboards and analytics interfaces that turn raw data into clear, fast decisions for you and your team.", ["Admin dashboard design", "Analytics and reporting UI", "Role-based access views", "Real-time data visualization", "Custom widget development", "Dashboard performance optimization", "Integration with existing APIs", "Ongoing support and maintenance"], "service-dark"],
  ["AI Automation", "We design and build AI-powered automation that removes manual work from your business — from customer-facing chatbots to internal workflows that run themselves.", ["AI chatbots and virtual assistants", "Workflow and task automation", "Custom AI integrations (LLM/API)", "Document and data processing automation", "AI-powered internal tools", "Third-party automation platform setup", "Automated reporting and alerts", "Ongoing support and maintenance"], "service-light"],
] as const;

// Every dialling code in the world, sorted by country name. The ISO code is the
// option value, not the dial code, because +1, +44, +7 and +212 are each shared
// by several countries.
export const countries: [string, string, string][] = [
  ["AF", "Afghanistan", "+93"],
  ["AL", "Albania", "+355"],
  ["DZ", "Algeria", "+213"],
  ["AS", "American Samoa", "+1684"],
  ["AD", "Andorra", "+376"],
  ["AO", "Angola", "+244"],
  ["AI", "Anguilla", "+1264"],
  ["AG", "Antigua & Barbuda", "+1268"],
  ["AR", "Argentina", "+54"],
  ["AM", "Armenia", "+374"],
  ["AW", "Aruba", "+297"],
  ["AU", "Australia", "+61"],
  ["AT", "Austria", "+43"],
  ["AZ", "Azerbaijan", "+994"],
  ["BS", "Bahamas", "+1242"],
  ["BH", "Bahrain", "+973"],
  ["BD", "Bangladesh", "+880"],
  ["BB", "Barbados", "+1246"],
  ["BY", "Belarus", "+375"],
  ["BE", "Belgium", "+32"],
  ["BZ", "Belize", "+501"],
  ["BJ", "Benin", "+229"],
  ["BM", "Bermuda", "+1441"],
  ["BT", "Bhutan", "+975"],
  ["BO", "Bolivia", "+591"],
  ["BA", "Bosnia & Herzegovina", "+387"],
  ["BW", "Botswana", "+267"],
  ["BR", "Brazil", "+55"],
  ["VG", "British Virgin Islands", "+1284"],
  ["BN", "Brunei", "+673"],
  ["BG", "Bulgaria", "+359"],
  ["BF", "Burkina Faso", "+226"],
  ["BI", "Burundi", "+257"],
  ["KH", "Cambodia", "+855"],
  ["CM", "Cameroon", "+237"],
  ["CA", "Canada", "+1"],
  ["CV", "Cape Verde", "+238"],
  ["KY", "Cayman Islands", "+1345"],
  ["CF", "Central African Republic", "+236"],
  ["TD", "Chad", "+235"],
  ["CL", "Chile", "+56"],
  ["CN", "China", "+86"],
  ["CO", "Colombia", "+57"],
  ["KM", "Comoros", "+269"],
  ["CG", "Congo - Brazzaville", "+242"],
  ["CD", "Congo - Kinshasa", "+243"],
  ["CK", "Cook Islands", "+682"],
  ["CR", "Costa Rica", "+506"],
  ["CI", "Côte d’Ivoire", "+225"],
  ["HR", "Croatia", "+385"],
  ["CU", "Cuba", "+53"],
  ["CW", "Curaçao", "+599"],
  ["CY", "Cyprus", "+357"],
  ["CZ", "Czechia", "+420"],
  ["DK", "Denmark", "+45"],
  ["DJ", "Djibouti", "+253"],
  ["DM", "Dominica", "+1767"],
  ["DO", "Dominican Republic", "+1809"],
  ["EC", "Ecuador", "+593"],
  ["EG", "Egypt", "+20"],
  ["SV", "El Salvador", "+503"],
  ["GQ", "Equatorial Guinea", "+240"],
  ["ER", "Eritrea", "+291"],
  ["EE", "Estonia", "+372"],
  ["SZ", "Eswatini", "+268"],
  ["ET", "Ethiopia", "+251"],
  ["FK", "Falkland Islands", "+500"],
  ["FO", "Faroe Islands", "+298"],
  ["FJ", "Fiji", "+679"],
  ["FI", "Finland", "+358"],
  ["FR", "France", "+33"],
  ["GF", "French Guiana", "+594"],
  ["PF", "French Polynesia", "+689"],
  ["GA", "Gabon", "+241"],
  ["GM", "Gambia", "+220"],
  ["GE", "Georgia", "+995"],
  ["DE", "Germany", "+49"],
  ["GH", "Ghana", "+233"],
  ["GI", "Gibraltar", "+350"],
  ["GR", "Greece", "+30"],
  ["GL", "Greenland", "+299"],
  ["GD", "Grenada", "+1473"],
  ["GP", "Guadeloupe", "+590"],
  ["GU", "Guam", "+1671"],
  ["GT", "Guatemala", "+502"],
  ["GG", "Guernsey", "+44"],
  ["GN", "Guinea", "+224"],
  ["GW", "Guinea-Bissau", "+245"],
  ["GY", "Guyana", "+592"],
  ["HT", "Haiti", "+509"],
  ["HN", "Honduras", "+504"],
  ["HK", "Hong Kong", "+852"],
  ["HU", "Hungary", "+36"],
  ["IS", "Iceland", "+354"],
  ["IN", "India", "+91"],
  ["ID", "Indonesia", "+62"],
  ["IR", "Iran", "+98"],
  ["IQ", "Iraq", "+964"],
  ["IE", "Ireland", "+353"],
  ["IM", "Isle of Man", "+44"],
  ["IL", "Israel", "+972"],
  ["IT", "Italy", "+39"],
  ["JM", "Jamaica", "+1876"],
  ["JP", "Japan", "+81"],
  ["JE", "Jersey", "+44"],
  ["JO", "Jordan", "+962"],
  ["KZ", "Kazakhstan", "+7"],
  ["KE", "Kenya", "+254"],
  ["KI", "Kiribati", "+686"],
  ["XK", "Kosovo", "+383"],
  ["KW", "Kuwait", "+965"],
  ["KG", "Kyrgyzstan", "+996"],
  ["LA", "Laos", "+856"],
  ["LV", "Latvia", "+371"],
  ["LB", "Lebanon", "+961"],
  ["LS", "Lesotho", "+266"],
  ["LR", "Liberia", "+231"],
  ["LY", "Libya", "+218"],
  ["LI", "Liechtenstein", "+423"],
  ["LT", "Lithuania", "+370"],
  ["LU", "Luxembourg", "+352"],
  ["MO", "Macao", "+853"],
  ["MG", "Madagascar", "+261"],
  ["MW", "Malawi", "+265"],
  ["MY", "Malaysia", "+60"],
  ["MV", "Maldives", "+960"],
  ["ML", "Mali", "+223"],
  ["MT", "Malta", "+356"],
  ["MH", "Marshall Islands", "+692"],
  ["MQ", "Martinique", "+596"],
  ["MR", "Mauritania", "+222"],
  ["MU", "Mauritius", "+230"],
  ["YT", "Mayotte", "+262"],
  ["MX", "Mexico", "+52"],
  ["FM", "Micronesia", "+691"],
  ["MD", "Moldova", "+373"],
  ["MC", "Monaco", "+377"],
  ["MN", "Mongolia", "+976"],
  ["ME", "Montenegro", "+382"],
  ["MS", "Montserrat", "+1664"],
  ["MA", "Morocco", "+212"],
  ["MZ", "Mozambique", "+258"],
  ["MM", "Myanmar", "+95"],
  ["NA", "Namibia", "+264"],
  ["NR", "Nauru", "+674"],
  ["NP", "Nepal", "+977"],
  ["NL", "Netherlands", "+31"],
  ["NC", "New Caledonia", "+687"],
  ["NZ", "New Zealand", "+64"],
  ["NI", "Nicaragua", "+505"],
  ["NE", "Niger", "+227"],
  ["NG", "Nigeria", "+234"],
  ["NU", "Niue", "+683"],
  ["KP", "North Korea", "+850"],
  ["MK", "North Macedonia", "+389"],
  ["NO", "Norway", "+47"],
  ["OM", "Oman", "+968"],
  ["PK", "Pakistan", "+92"],
  ["PW", "Palau", "+680"],
  ["PS", "Palestine", "+970"],
  ["PA", "Panama", "+507"],
  ["PG", "Papua New Guinea", "+675"],
  ["PY", "Paraguay", "+595"],
  ["PE", "Peru", "+51"],
  ["PH", "Philippines", "+63"],
  ["PL", "Poland", "+48"],
  ["PT", "Portugal", "+351"],
  ["PR", "Puerto Rico", "+1787"],
  ["QA", "Qatar", "+974"],
  ["RE", "Réunion", "+262"],
  ["RO", "Romania", "+40"],
  ["RU", "Russia", "+7"],
  ["RW", "Rwanda", "+250"],
  ["WS", "Samoa", "+685"],
  ["SM", "San Marino", "+378"],
  ["ST", "São Tomé & Príncipe", "+239"],
  ["SA", "Saudi Arabia", "+966"],
  ["SN", "Senegal", "+221"],
  ["RS", "Serbia", "+381"],
  ["SC", "Seychelles", "+248"],
  ["SL", "Sierra Leone", "+232"],
  ["SG", "Singapore", "+65"],
  ["SX", "Sint Maarten", "+1721"],
  ["SK", "Slovakia", "+421"],
  ["SI", "Slovenia", "+386"],
  ["SB", "Solomon Islands", "+677"],
  ["SO", "Somalia", "+252"],
  ["ZA", "South Africa", "+27"],
  ["KR", "South Korea", "+82"],
  ["SS", "South Sudan", "+211"],
  ["ES", "Spain", "+34"],
  ["LK", "Sri Lanka", "+94"],
  ["KN", "St. Kitts & Nevis", "+1869"],
  ["LC", "St. Lucia", "+1758"],
  ["VC", "St. Vincent & Grenadines", "+1784"],
  ["SD", "Sudan", "+249"],
  ["SR", "Suriname", "+597"],
  ["SE", "Sweden", "+46"],
  ["CH", "Switzerland", "+41"],
  ["SY", "Syria", "+963"],
  ["TW", "Taiwan", "+886"],
  ["TJ", "Tajikistan", "+992"],
  ["TZ", "Tanzania", "+255"],
  ["TH", "Thailand", "+66"],
  ["TL", "Timor-Leste", "+670"],
  ["TG", "Togo", "+228"],
  ["TO", "Tonga", "+676"],
  ["TT", "Trinidad & Tobago", "+1868"],
  ["TN", "Tunisia", "+216"],
  ["TR", "Turkey", "+90"],
  ["TM", "Turkmenistan", "+993"],
  ["TC", "Turks & Caicos Islands", "+1649"],
  ["TV", "Tuvalu", "+688"],
  ["UG", "Uganda", "+256"],
  ["UA", "Ukraine", "+380"],
  ["AE", "United Arab Emirates", "+971"],
  ["GB", "United Kingdom", "+44"],
  ["US", "United States", "+1"],
  ["UY", "Uruguay", "+598"],
  ["UZ", "Uzbekistan", "+998"],
  ["VU", "Vanuatu", "+678"],
  ["VA", "Vatican City", "+379"],
  ["VE", "Venezuela", "+58"],
  ["VN", "Vietnam", "+84"],
  ["EH", "Western Sahara", "+212"],
  ["YE", "Yemen", "+967"],
  ["ZM", "Zambia", "+260"],
  ["ZW", "Zimbabwe", "+263"],
];
