export const services = [
  { title: "App Development", icon: "fa-mobile-alt", description: "Native and cross-platform mobile apps for Android, iOS, and beyond, built for performance and scale." },
  { title: "SaaS Website", icon: "fa-cloud", description: "Conversion-focused SaaS marketing sites and landing pages built to turn visitors into subscribers." },
  { title: "PaaS Website", icon: "fa-cubes", description: "Platform-as-a-service websites and portals designed for onboarding, integrations, and scale." },
  { title: "Web Development", icon: "fa-code", description: "Custom high-performance websites and web applications tailored to your business goals." },
  { title: "WordPress Development", icon: "fa-wordpress", description: "Fast, responsive, SEO-friendly WordPress websites for businesses and online brands." },
  { title: "Custom Software", icon: "fa-laptop-code", description: "Bespoke software built end-to-end around your exact business processes and requirements." },
  { title: "Custom Web Software", icon: "fa-globe", description: "Custom web-based applications and internal tools, built and hosted entirely in the browser." },
  { title: "Custom Dashboard", icon: "fa-tachometer-alt", description: "Data-rich admin dashboards and analytics interfaces built for clarity and fast decision-making." },
  { title: "AI Automation", icon: "fa-brain", description: "AI-powered workflows, chatbots, and process automation that cut manual work and scale with your business." },
];

export const portfolioItems = [
  ["Enterprise Task Management App", "App Development", "app", "fa-mobile-alt", "A cross-platform mobile app for assigning, tracking, and reporting on team tasks in real time across large organizations."],
  ["Fitness Tracking Mobile App", "App Development", "app", "fa-mobile-alt", "A native fitness app with workout logging, progress charts, and personalized plans built for daily engagement."],
  ["SaaS Analytics Platform Website", "SaaS Website", "saas", "fa-cloud", "A conversion-focused marketing site and product tour for a data analytics SaaS, built to turn trial signups into subscribers."],
  ["Subscription Billing SaaS Site", "SaaS Website", "saas", "fa-cloud", "A pricing-led SaaS website with plan comparison, billing FAQs, and a streamlined signup flow to reduce checkout drop-off."],
  ["Developer Platform Portal", "PaaS Website", "paas", "fa-cubes", "A developer-facing PaaS portal with API docs, onboarding guides, and an integration marketplace to speed up adoption."],
  ["Corporate Business Website", "Web Development", "web", "fa-code", "A fast, SEO-optimized corporate website with a custom CMS, built to represent the brand and generate qualified leads."],
  ["E-commerce Web Application", "Web Development", "web", "fa-code", "A custom e-commerce platform with product catalog, cart, and checkout, built for performance at scale."],
  ["Real Estate WordPress Website", "WordPress Development", "wordpress", "fa-wordpress", "A responsive WordPress site with property listings, search filters, and lead-capture forms for a real estate brand."],
  ["Restaurant WordPress Website", "WordPress Development", "wordpress", "fa-home", "A WordPress website with online menu, reservation booking, and location pages for a multi-branch restaurant."],
  ["Custom Inventory Management System", "Custom Software", "software", "fa-laptop-code", "A bespoke inventory system with stock tracking, supplier management, and automated low-stock alerts."],
  ["Client Portal Web Application", "Custom Web Software", "websoftware", "fa-globe", "A browser-based client portal for project updates, file sharing, and invoicing, replacing scattered email threads."],
  ["Business Analytics Dashboard", "Custom Dashboard", "dashboard", "fa-tachometer-alt", "A real-time analytics dashboard turning raw business data into clear charts and exportable reports for decision-makers."],
] as const;

export const serviceDetails = [
  ["App Development - Android, iOS and Cross-Platform", "We build powerful, user-friendly mobile applications for Android, iOS, and cross-platform environments, engineered for performance from the first line of code.", ["Native Android app development", "iOS app development", "Cross-platform apps", "UI/UX for mobile apps", "App testing and deployment", "API integration", "App store optimization", "Maintenance and updates"], "service-light"],
  ["SaaS Website and Product Design", "We design and build SaaS websites, landing pages, and product interfaces engineered to turn visitors into subscribers and subscribers into long-term customers.", ["SaaS landing page design", "SaaS dashboard UI/UX", "Pricing page design", "Feature page design", "SaaS website development", "User onboarding design", "Subscription management", "Conversion optimization"], "service-dark"],
  ["PaaS Website and Platform Design", "We design and build platform-as-a-service websites and portals — the front door to your platform, built for developer onboarding, integrations, and scale.", ["Platform landing page design", "Developer portal design", "API documentation pages", "Integration marketplace pages", "Onboarding flow design", "Usage dashboard design", "Multi-tenant architecture support", "Conversion optimization"], "service-light"],
  ["Professional Web Development", "We develop custom, high-performance websites and web applications tailored to your brand and business goals, optimized for speed, SEO, and user experience.", ["Custom website development", "E-commerce websites", "Business websites", "Portfolio websites", "Landing pages", "Web application development", "CMS integration", "Performance optimization", "Security implementation"], "service-dark"],
  ["Responsive WordPress Website Development", "We build fast, responsive, SEO-friendly, and professional WordPress websites for businesses, agencies, portfolios, and online brands.", ["Business websites", "Portfolio websites", "Agency websites", "Landing pages", "Blog websites", "Elementor websites", "Contact forms", "Speed optimization", "Mobile responsive design"], "service-light"],
  ["Custom Software Development", "We build bespoke software end-to-end, engineered around your exact business processes rather than forcing your workflow to fit an off-the-shelf product.", ["Requirements and process mapping", "Custom backend systems", "Database design and architecture", "Third-party API integration", "Legacy system modernization", "Automated testing", "Deployment and DevOps setup", "Ongoing support and maintenance"], "service-dark"],
  ["Custom Web Software Development", "We build custom web-based applications and internal tools that run entirely in the browser — no installs, accessible from anywhere, built around your team's exact workflow.", ["Internal tools and admin panels", "Workflow and process automation", "Multi-user web applications", "Role-based access control", "Real-time data features", "Cloud deployment and hosting", "API and integration development", "Ongoing support and maintenance"], "service-light"],
  ["Custom Dashboard Development", "We design and build data-rich admin dashboards and analytics interfaces that turn raw data into clear, fast decisions for you and your team.", ["Admin dashboard design", "Analytics and reporting UI", "Role-based access views", "Real-time data visualization", "Custom widget development", "Dashboard performance optimization", "Integration with existing APIs", "Ongoing support and maintenance"], "service-dark"],
  ["AI Automation", "We design and build AI-powered automation that removes manual work from your business — from customer-facing chatbots to internal workflows that run themselves.", ["AI chatbots and virtual assistants", "Workflow and task automation", "Custom AI integrations (LLM/API)", "Document and data processing automation", "AI-powered internal tools", "Third-party automation platform setup", "Automated reporting and alerts", "Ongoing support and maintenance"], "service-light"],
] as const;
